-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.128 s <<< FAILURE! - in TestSuite
test_1(org.testNg.runTest)  Time elapsed: 0.15 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testNg.runTest.test_1() didn't finish within the time-out 1

