<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="/Users/tomorrowisly/FactoryMode"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="0.386">
  <properties />
            <testcase name="test_1" time="0.024" classname="org.testNg.runTest">
                <failure type="org.testng.internal.thread.ThreadTimeoutException"
                  message="Method org.testNg.runTest.test_1() didn&apos;t finish within the time-out 1"
              >
<![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testNg.runTest.test_1() didn't finish within the time-out 1
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test_2" time="0.006" classname="org.testNg.runTest" />
                <testcase name="test_2" time="0.356" classname="org.testNg.runTest" />
      
</testsuite>
